name: ZombieEscape
main: xyz.acrylicstyle.zombieescape.ZombieEscape
version: 0.0.1
depend: [ProtocolLib]

commands:
  zombieescape:
    description: "Zombie Escape"
    usage: /<command>
  setsponsor:
    description: "Add a new sponsored player."
    usage: /<command> <player>
    aliases: ["sponsor"]
    permission: zombieescape.setsponsor
  removesponsor:
    description: "Remove a sponsored player."
    usage: /<command> <player>
    permission: zombieescape.removesponsor
  setspawn:
    description: "Sets spawn of zombie/player."
    usage: /<command> <zombie/player> <0, 1, 2, 3, ...>
    permission: zombieescape.setspawn
  removespawn:
    description: "Remove spawn."
    usage: /<command> <zombie/player> <0, 1, 2, 3, ...> or /<command> world
    aliases: ["unsetspawn", "delspawn", "deletespawn"]
    permission: zombieescape.removespawn
  setcp:
    description: "Sets checkpoint in-game. Recommended command block."
    usage: /<command> <0, 1, 2, 3, ...>
    aliases: ["cp", "checkpoint"]
    permission: zombieescape.setcp
  suicide:
    description: "Kills yourself."
    usage: /<command>
  startgame:
    description: "Starts game."
    usage: /<command>
    permission: zombieescape.startgame
  endgame:
    description: "Ends ongoing game."
    usage: /<command>
    permission: zombieescape.endgame
  check:
    description: "Check configuration."
    usage: /<command>
    permission: zombieescape.check
    aliases: ["recheck"]
  addwall:
    description: "Add a wall."
    usage: /<command>
    permission: zombieescape.addwall
    aliases: ["putwall"]
  deletewall:
    description: "Deletes a wall"
    usage: /<command>
    permission: zombieescape.deletewall
    aliases: ["removewall"]
  setstatus:
    description: "Set status of the game."
    usage: /<command>
    permission: zombieescape.setstatus
  setmapname:
    description: "Set name of the map."
    usage: /<command>
    permission: zombieescape.setmapname
  setmap:
    description: "Set map"
    usage: /<command>
    permission: zombieescape.setmap
  vote:
    description: "Vote for map!"
    usage: /<command> <map>
